FROM php:8.2-apache
WORKDIR /var/www/html
COPY authorize.php /var/www/html/authorize.php
COPY login.php /var/www/html/login.php
COPY token.php /var/www/html/token.php
COPY users.json /var/www/html/users.json
COPY utils.php /var/www/html/utils.php

EXPOSE 80