name: Deploy ACI

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_MCSE }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init
        working-directory: ./step6

      - name: Terraform Apply com Retry
        run: |
          max=3
          count=1

          until [ $count -gt $max ]
          do
            echo "=============================="
            echo "Tentativa $count de $max"
            echo "=============================="

            terraform apply -auto-approve && break

            if [ $count -eq $max ]; then
              echo "❌ Todas as tentativas falharam"
              exit 1
            fi

            echo "⏳ Falhou... aguardando 30s antes da próxima tentativa"
            sleep 300

            count=$((count+1))
          done
        working-directory: ./step6