name: Deploy ACI

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_MCSE }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init
        working-directory: ./step6

      - name: Terraform Apply (padrão step3)
        run: |
          for i in 1 2; do
            echo "=============================="
            echo "Tentativa $i de deploy"
            echo "=============================="

            terraform apply -auto-approve && break

            echo "Falhou na tentativa $i. Aguardando 30 minutos..."
            
          done
        working-directory: ./step6