name: Terraform Step3 (ACI Deploy)

on:
  workflow_call:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_MCSE }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./step3

      - name: Terraform Apply (retry)
        run: |
          set -e

          for i in 1 2 3; do
            echo "=============================="
            echo "Tentativa $i de deploy"
            echo "=============================="

            terraform apply -auto-approve && exit 0

            echo "Falhou na tentativa $i..."

            if [ $i -lt 3 ]; then
              echo "Aguardando 60s antes de tentar novamente..."
              sleep 60
            fi
          done

          exit 1
        working-directory: ./step3