name: Terraform Step3 (ACI Deploy)

on:
  workflow_call:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_MCSE }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./step3

      - name: Terraform Apply com Retry
        run: |
          for i in 1 2; do
            echo "=============================="
            echo "Tentativa $i de deploy"
            echo "=============================="

            terraform apply -auto-approve && break

            echo "Falhou na tentativa $i. Aguardando 30 min antes de tentar novamente..."
            sleep 1800
          done
        working-directory: ./step3